cqfn/aibolit

aibolit/patterns/assert_in_code/assert_in_code.py, aibolit/patterns/classic_setter/classic_setter.py, aibolit/patterns/empty_rethrow/empty_rethrow.py, aibolit/patterns/er_class/er_class.py, aibolit/patterns/force_type_casting_finder/force_type_casting_finder.py, aibolit/patterns/implements_multi/implements_multi.py, aibolit/patterns/instanceof/instance_of.py, aibolit/patterns/many_primary_ctors/many_primary_ctors.py, aibolit/patterns/method_chaining/method_chaining.py, aibolit/patterns/multiple_try/multiple_try.py, aibolit/patterns/nested_blocks/nested_blocks.py, aibolit/patterns/null_check/null_check.py, aibolit/patterns/partial_synchronized/partial_synchronized.py, aibolit/patterns/redundant_catch/redundant_catch.py, aibolit/patterns/return_null/return_null.py, aibolit/patterns/string_concat/string_concat.py, aibolit/patterns/supermethod/supermethod.py, aibolit/patterns/this_finder/this_finder.py, aibolit/patterns/var_decl_diff/var_decl_diff.py, aibolit/patterns/var_middle/var_middle.py, aibolit/utils/ast.py
For #131:
- Implemented `Ast` class, which represents the Abstract Syntax Tree from some java file
- Removed `__file_to_ast`  from pattern classes
- Left puzzle to implement `Ast` decorators where `__file_to_ast` needs to be extended
=> For #131: implementes Ast class

aibolit/patterns/string_concat/string_concat.py
For #159 :  Looks like #159 is outdated, `string_concat` does not uses `__file_to_ast implementation` method anymore. So I think that there's no point in making a NoComments implementation of AST right now, it wouldn't be used anywhere.
Removed the outdated method and the todo.
=> For #159: removed outdated code and todo

README.md, aibolit/__main__.py, test/recommend/test_recommend_pipeline.py
=> Reorganized console output

Makefile, aibolit/patterns/var_middle/var_middle.py, aibolit/utils/ast.py, test/utils/simple_class.java, test/utils/test_ast.py
I decided to use networkx library to wrap javalang AST. It has ability to attach any attributes to nodes and edges and has some algorithms for traversing a graph, which could be helpful.
As for now node only has type and line number if provided. Two new types were added manually - string (names and keywords) and collections (of those strings).
=> Wrapper for javalang package.

aibolit/patterns/non_final_attribute/non_final_attribute.py, test/patterns/non_final_attribute/AttributeInInterface.java, test/patterns/non_final_attribute/test_non_final_attribute.py
For #357: 
- changed `non_final_attribute` pattern to ignore non final attributes in interface
- added test to this new condition
=> For #357: non_final_attribute in interfaces

aibolit/__main__.py
=> Ignore patterns with suppress_warnings

aibolit/ast_framework/__init__.py, aibolit/ast_framework/ast.py, aibolit/ast_framework/ast_node.py, aibolit/patterns/implements_multi/implements_multi.py, aibolit/patterns/joined_validation/joined_validation.py, aibolit/patterns/return_null/return_null.py, aibolit/patterns/supermethod/supermethod.py, requirements.txt, test/patterns/return_null/test_return_null.py, test/patterns/supermethod/test_supermethod.py
Patterns `joined_validation`, `return_null` and `supermethod`  are rewriten to use`ASTNode`, which simplified their code.
Few auxiliary methods have been added to `AST`:
- You can now iterate over all nodes of `AST` with
```python
for node in ast:
pass
```
- You can iterate over `AST` nodes with some type, by `get_proxy_nodes` method. Its name is temporal and will be changed to `get_nodes` when current `get_nodes` method will be deleted.
**NOTICE:** almost all `AST` methods are marked as deprecated. Use `ASTNode` interface to access children and attributes.
=> Patterns refactor with ASTNode API.

aibolit/ast_framework/ast.py, aibolit/ast_framework/ast_node.py, aibolit/ast_framework/java_class.py, aibolit/ast_framework/java_class_field.py, aibolit/ast_framework/java_class_method.py, aibolit/ast_framework/java_package.py, aibolit/patterns/assert_in_code/assert_in_code.py, aibolit/patterns/force_type_casting_finder/force_type_casting_finder.py, aibolit/patterns/if_return_if_detection/if_detection.py, aibolit/patterns/instanceof/instance_of.py, aibolit/patterns/multiple_while/multiple_while.py, aibolit/patterns/non_final_class/non_final_class.py, aibolit/utils/cfg_builder.py
- `ASTNoed` got method to retrieve subtree with itself as a root
-  Classes `JavaPackage`, `JavaClass`, `JavaClassMethod`, `JavaClassField` are now deprecated. Its functionality should become computed fields in `ASTNode`.
- Patterns `non_final_class`, `multiple_while`, `instance_of`, `if_detection`, `for_type_casting_finder`, `assert_in_code` are transitioned to new ASTNode API.
- `cfg_builder` now use new API too.
=> Old patterns reafctored

aibolit/patterns/many_primary_ctors/many_primary_ctors.py, aibolit/patterns/method_siblings/method_siblings.py
=> refactored method_siblings

aibolit/patterns/redundant_catch/redundant_catch.py, test/patterns/redundant_catch/test_redundant_catch.py
Solved in case of #528 
Also test was change because of previous error (you can check the sourse code and make sure that this code structure should be detected too
=> Redundant_catch refactored 

aibolit/__main__.py, test/integration/test_model.py
fix https://github.com/cqfn/aibolit/issues/574
1) request #594 has and interface to use `test` function. But we have to retrain model, since that function is not included yet in model.pkl
2) integration test is added with feature selection
3) You can use the following way:
```
selected_patterns = ['P18', 'P9', 'M2', 'M5']
model.fit_regressor(train_df, target, selected_patterns)
```
So, we select features we need. The model will be trained using only features which are passed to function (if we pass them), otherwise all features will be used.
See full test (test_train_with_selected_features.py) for detailed information.
=> Allow model training with feature selection

aibolit/extract_method_baseline/extract_semantic.py, test/extract_method_baseline/SimpleMethods.java, test/extract_method_baseline/test_extract_semantic.py
Fix #634
Extracts semantic from methods. First step for Baseline. Currently only plain statements are supported. All statements, which alow nesting will be added in following PR.
=> Extract semantic

aibolit/ast_framework/ast_node.py, aibolit/extract_method_baseline/extract_semantic.py
Fix #638.
Add ability to launch `extract_semantic...` functions from CLI.
Help message:
```bash
python -m aibolit.extract_method_baseline.extract_semantic -h
usage: extract_semantic.py [-h] -f FILE [-c CLASS_NAME] [-m METHOD_NAME]
Extracts semantic from specified methods
optional arguments:
-h, --help            show this help message and exit
-f FILE, --file FILE  File path to JAVA source code for extracting semantic
-c CLASS_NAME, --class CLASS_NAME
Class name of method to parse, if omitted all classes are considered
-m METHOD_NAME, --method METHOD_NAME
Method name to parse, if omitted all method are considered
```
You can filter methods by their names and class names they contained in.
Output example:
```bash
python -m aibolit.extract_method_baseline.extract_semantic -f …
```
=> CLI app to extract semantic from methods.

aibolit/ast_framework/ast_node.py, requirements.txt
In this PR we drop dependence on `cached_property` package
in favor of `functools.cached_property` decorator,
which is a part of Python standard library since Python 3.8.
Closes #703
=> Drop dependence on cached_property package

Makefile, requirements.txt, test/metrics/hv/__init__.py, test/metrics/hv/test_all_types.py, test/metrics/npath/__init__.py, test/metrics/npath/test_all_types.py
In this PR we use `pytest` instead of `unittest` framework for running automated tests.
1. Add requirements: `pytest` and `pytest-cov` (for coverage)
2. Use `pytest` in `make test` command
Closes #684
=> Use pytest framework instead of unittest

.github/workflows/ty.yml, aibolit/__main__.py, aibolit/metrics/countLeaves/numberofleaves.py, aibolit/patterns/var_decl_diff/var_decl_diff.py, aibolit/utils/ast_builder.py, aibolit/utils/cfg_builder.py, aibolit/utils/encoding_detector.py, aibolit/utils/filter.py, aibolit/utils/java_parser.py, aibolit/utils/lines.py, scripts/02-filter-and-move.py, test/recommend/test_recommend_pipeline.py
This PR fixes multiple typing errors related to `aibolit/utils` subpackage.
Before (master branch):
```
└➜ uvx ty check | tail -n 1
WARN ty is pre-release software and not ready for production use. Expect to encounter bugs, missing features, and fatal errors.
Found 157 diagnostics
```
This PR:
```
└➜ uvx ty check | tail -n 1
WARN ty is pre-release software and not ready for production use. Expect to encounter bugs, missing features, and fatal errors.
Found 53 diagnostics
```
No remaining issues related to `utils`.
```
└➜ uvx ty check | grep utils
WARN ty is pre-release software and not ready for production use. Expect to encounter bugs, missing features, and fatal errors.
```
When fixing typing errors I had to ignore some of them as shown in the diffs below.
I checked that …
=> TYP: fix typing errors in aibolit/utils

aibolit/__main__.py
This change handles non-OK status code when requesting the latest aibolit version from PyPI.
`response.raise_for_status()` succeeds if status code is less than 400, otherwise raises `HTTPError`, which we then handle on the caller's side https://docs.python-requests.org/en/latest/_modules/requests/models/#Response.raise_for_status
Closes #722
=> FIX: handle non-OK status code when requesting aibolit version

aibolit/metrics/external_methods_called/external_methods_called.py, aibolit/metrics/local_methods_calls/local_methods_calls.py, aibolit/metrics/ncss/ncss.py, aibolit/patterns/bidirect_index/bidirect_index.py, aibolit/patterns/mutable_index/mutable_index.py, aibolit/patterns/non_final_argument/non_final_argument.py, aibolit/utils/cfg_builder.py, aibolit/utils/java_parser.py, aibolit/utils/lines.py, pyproject.toml
This PR fixes unexpected indentations in docstrings,
which used to trigger errors when building docs.
Closes #719
=> FIX: unexpected indents in docstrings

aibolit/patterns/send_null/send_null.py, test/patterns/send_null/test_send_null.py
This PR adds a missing test case to cover a line in `SendNull`.
The test case is taken from [test/integration/samples/IntKeyMap.java](https://github.com/cqfn/aibolit/blob/master/test/integration/samples/IntKeyMap.java#L705).
Originally I implemented a refactoring of `SendNull.value`, so that we compare `val.value == 'null'`, however it fails if `val.value` is `ASTNode`, which does not have `__eq__` defined for comparison with strings.
Thus, I reverted the refactoring and only added the test case.
Closes #709
=> Add a missing test case for SendNull

aibolit/metrics/npath/main.py, requirements.txt
This PR suggests using the newest version of `beautifulsoup4==4.13.4`.
They removed the deprecated parameter `strip_cdata` starting from version 4.13.0.
Changelog: https://git.launchpad.net/beautifulsoup/tree/CHANGELOG
Closes #730
=> Fix bs4-related deprecation warning

test/patterns/classic_getter/test_classic_getter.py
This PR adds a failing test on classic getter pattern where `this` reference is used.
Xref: #736
=> Add a failing test on ClassicGetter

.github/workflows/latexmk.yml
Drop installation of `texlive-fonts-recommended` from `latexmk` workflow
as we expect that the newer docker image `yegor256/latex` already contains the required fonts.
Closes #724 
Xref: https://github.com/yegor256/dockers/issues/30
=> Drop texlive-fonts-recommended from latexmk workflow

aibolit/patterns/classic_getter/classic_getter.py, test/patterns/classic_getter/test_classic_getter.py
In this PR we add a case where `getSomething` method
does not return anything.
This is the only remaining case to fully cover `ClassicGetter` pattern.
Closes #762
=> Add test case to fully cover `ClassicGetter`

aibolit/patterns/non_final_argument/non_final_argument.py, test/patterns/non_final_argument/test_non_final_argument.py
This PR implements `NonFinalArgument` pattern.
I noticed that at the moment of writing the issue is already closed by PDD, but this apparently happened due to my recent PR on formatting docstrings to avoid over-indentation #721.
Closes #485
=> Implement pattern `NonFinalArgument`

test/integration/check/java/com/artipie/docker/DockerProxy.java
This PR drop an irrelevant puzzle in `DockerProxy.java`. Apparently the file `DockerProxy.java` was taken from another project for a purpose of an integration testing fixture.
However, `0pdd` bot treated the puzzle in the body of the file as a real one.
Closes #754
=> Drop irrelevant puzzle in `DockerProxy.java`

test/patterns/bidirect_index/test_bidirect_index.py
This PR fixes expected offending lines in tests, matching the pattern `BidirectIndex`,
by shifting them by 3, which account for the copyright statement and a newline.
One puzzle has been added, since I suppose there was an error in the original test.
Closes #772
=> Fix expected pattern matching lines in `BidirectIndexTestCase`

test/patterns/bidirect_index/test_bidirect_index.py
In this PR we qualify the test case
`test_bidirect_index_hidden_scope_true` as a non-pattern matching.
Closes #776
=> Qualify test case on `BidirectIndex` as non-pattern

test/integration/check/java/com/artipie/metrics/memory/InMemoryMetrics.java
Drop puzzle from `InMemoryMetrics.java` integration test fixture. The puzzle belongs to a separate project where this file was taken from and thus must be removed to clear the backlog.
Closes #755
=> Drop puzzle from `InMemoryMetrics.java` intgr test fixture

test/integration/check/java/com/artipie/VertxMain.java
This PR drop an irrelevant puzzle from `VertxMain.java`. The puzzle belongs to another project, where this java file was taken from as a part of an integration test fixture.
Closes #749
=> Drop irrelevant puzzle from `VertxMain.java`

test/integration/check/java/com/artipie/SliceFromConfig.java
This PR removes an irrelevant puzzle from `SliceFromConfig.java`. The puzzle belongs to another project where this file was taken from as a part of the integration test suite fixture.
Closes #748
=> Drop irrelevant puzzle from `SliceFromConfig.java`

aibolit/metrics/npath/main.py, test/metrics/npath/test_all_types.py
In this PR we added a new class `MvnFreeNPathMetric`, which implements computation of NPath metric, without using an external process, as opposed to the original `NPathMetric` implementation.
Until `MvnFreeNPathMetric` fully implements all language constructs we must keep `NPathMetric` as it is now.
Then we will use `MvnFreeNPathMetric` as a part of `NPathMetric`.
Closes #798
=> Add `MvnFreeNPathMetric` for `if` statements
