cqfn/aibolit

aibolit/scripts/03-find-patterns.py
requirements.txt

Script to calculate AST patterns by provided list of java files

patterns script

---

aibolit/metrics/entropy/README.md
aibolit/metrics/entropy/entropy.py
requirements.txt
test/metrics/entropy/sample-1.java
test/metrics/entropy/test_entropy.py

Metric to calculate code entropy

Code entropy metric

---

aibolit/scripts/02-calculate-metrics.py

Pull request for Issue: [Implement metrics file for Java repositories files](https://github.com/yegor256/aibolit/issues/12)
Implemented logic:
- Get file names list from predefined directory and file name
- Create predefined number of threads to calculate metrics
- Calculate metrics for each file and store in output predefined csv file

Task #12 Implement calculate java files metrics script

---

aibolit/java_file_checker.py
run_var_middle.py

need to calculate 2 patterns  in parallel
https://github.com/yegor256/aibolit/issues/26
Also, https://github.com/yegor256/aibolit/issues/28

Python script for parallel calculation of patterns

---

scripts/01-fetch-github.py

Remove logic related to filtering out java files and creation csv file

Task #7 Enhance got repositories download script

---

scripts/01-fetch-github.py

To add new optinal integer parameter for download git repositories script used Argparse Python package

Task #31 Adding repos optional integer parameter to download git repositories

---

requirements.txt
scripts/02-filter-and-move.py
scripts/03-calculate-metrics.py
scripts/05-calculate-rs.py
scripts/Makefile

some script improvements

---

aibolit/patterns/var_middle/var_middle.py
test/patterns/var_middle/3.java
test/patterns/var_middle/4.java
test/patterns/var_middle/test_var_middle.py

The issue with var in the middle is fixed, tests are added

fixed var in the middle  for multi-line statements and empty lines

---

aibolit/patterns/var_decl_diff/README.md
aibolit/patterns/var_decl_diff/var_decl_diff.py
aibolit/patterns/var_middle/var_middle.py
test/patterns/var_decl_diff/1.java
test/patterns/var_decl_diff/2.java
test/patterns/var_decl_diff/3.java
test/patterns/var_decl_diff/4.java
test/patterns/var_decl_diff/test_var_decl_diff.py
test/patterns/var_middle/3.java
test/patterns/var_middle/4.java
test/patterns/var_middle/test_var_middle.py

This pattern returns lines where variable first time used but declared more than specific number of lines ago. This specific number is the parameter.

Var diff declaration first usage

---

aibolit/__main__.py
aibolit/metrics/spaces/SpaceCounter.py
aibolit/patterns/method_chaining/method_chaining.py
aibolit/patterns/string_concat/string_concat.py
aibolit/utils/utils.py
scripts/04-find-patterns.py
test/metrics/spaces/TestSpaces.py
test/patterns/method_chaining/EmptyMethodChain.java
test/patterns/method_chaining/FakeChain.java
test/patterns/method_chaining/HolyMolyNestedChain.java
test/patterns/method_chaining/MachineLearningGetResultsIT.java
test/patterns/method_chaining/MethodChain.java
test/patterns/method_chaining/MethodChainAnonymousClass.java
test/patterns/method_chaining/MethodChainAnonymousClassEmpty.java
test/patterns/method_chaining/MethodChainInDifferentMethods.java
test/patterns/method_chaining/MethodChainNestedClass.java
test/patterns/method_chaining/MethodChainNewObjectMethods.java
test/patterns/method_chaining/MethodChainSeveral.java
test/patterns/method_chaining/NestedChainWIthThis.java
test/patterns/method_chaining/NestedChainWithSimpleMethodInvocation.java
test/patterns/method_chaining/SmallestChain.java
test/patterns/method_chaining/WithoutObjectCreating.java
test/patterns/method_chaining/test_method_chaining.py
test/patterns/var_middle/test_loc.py

New pattern has been added. It finds all method chaining
#49

Method Chaining

---

test/patterns/var_decl_diff/4.java
test/patterns/var_decl_diff/test_var_decl_diff.py

I've added one more test case to test pattern "Line diff between usage and declaration of a variable".

one more test for multi-line function call

---

aibolit/patterns/var_middle/README.md
aibolit/patterns/var_middle/var_middle.py
test/patterns/var_middle/5.java
test/patterns/var_middle/6.java
test/patterns/var_middle/test_var_middle.py

Var in the middle patterns now works with nested classes and methods.

var in the middle pattern now works with nested classes and methods

---

scripts/04-find-patterns.py

https://github.com/yegor256/aibolit/issues/69

FIx patterns

---

scripts/07-merge.py

https://github.com/yegor256/aibolit/issues/67

Now merge.py merges pmd.metrics

---

scripts/02-filter-and-move.py

https://github.com/yegor256/aibolit/issues/64

Fix with lower cased dir

---

aibolit/patterns/supermethod/supermethod.py

https://github.com/yegor256/aibolit/issues/71

Fix super, it fails when arguments in javalang was not a list

---

PATTERNS.md

Here we are going to describe the patterns we designed.

Patterns dictionary Draft

---

aibolit/__main__.py

https://github.com/yegor256/aibolit/issues/81

Fix for ncss, now it's ready

---

aibolit/__main__.py
aibolit/patterns/string_concat/string_concat.py
test/patterns/string_concat/CliFlags.java
test/patterns/string_concat/ConcatInPrint.java
test/patterns/string_concat/test_concat_string.py

Fix lines number for concat pattern
https://github.com/yegor256/aibolit/issues/102

Fix lines number for concat pattern

---

aibolit/patterns/implements_multi/implements_multi.py
test/patterns/implements_multi/AnimatableSplitDimensionPathValue.java
test/patterns/implements_multi/AnimatableTransform.java
test/patterns/implements_multi/AuditEventModelProcessor.java
test/patterns/implements_multi/BaseKeyframeAnimation.java
test/patterns/implements_multi/Configuration.java
test/patterns/implements_multi/FJIterateTest.java
test/patterns/implements_multi/FJListProcedureRunner.java
test/patterns/implements_multi/FillContent.java
test/patterns/implements_multi/KeyProviderCryptoExtension.java
test/patterns/implements_multi/OsSecureRandom.java
test/patterns/implements_multi/RectangleContent.java
test/patterns/implements_multi/SequenceFile.java
test/patterns/implements_multi/test_implements_multi.py

Added new anti-pattern: multiple inheritance of interfaces.
Added tests for given pattern.

First version

---

aibolit/patterns/er_class/er_class.py
test/patterns/er_class/AnimatableSplitDimensionPathValue.java
test/patterns/er_class/AnimatableTransform.java
test/patterns/er_class/AuditEventModelProcessor.java
test/patterns/er_class/BaseKeyframeAnimation.java
test/patterns/er_class/Configuration.java
test/patterns/er_class/FJIterateTest.java
test/patterns/er_class/FJListProcedureRunner.java
test/patterns/er_class/FillContent.java
test/patterns/er_class/KeyProviderCryptoExtension.java
test/patterns/er_class/OsSecureRandom.java
test/patterns/er_class/RectangleContent.java
test/patterns/er_class/SequenceFile.java
test/patterns/er_class/test_er_class.py

New pattern for class declarations with name containing words:
'manager','controller','router','dispatcher','printer','writer','reader','parser','generator','renderer','listener','producer','holder','interceptor'
issue #91

Pattern branch

---

aibolit/__main__.py
aibolit/patterns/return_null/return_null.py
setup.py
test/patterns/return_null/Anonymous.java
test/patterns/return_null/Empty.java
test/patterns/return_null/Simple.java
test/patterns/return_null/With_Ternary.java
test/patterns/return_null/WithoutTernary.java
test/patterns/return_null/test_return_null.py

https://github.com/yegor256/aibolit/issues/97

Return null pattern

---

aibolit/patterns/er_class/er_class.py
aibolit/patterns/redundant_catch/redundant_catch.py
test/patterns/redundant_catch/BothCatches.java
test/patterns/redundant_catch/CatchWithFunctions.java
test/patterns/redundant_catch/MultipleCatch.java
test/patterns/redundant_catch/SequentialCatch.java
test/patterns/redundant_catch/SequentialCatchTry.java
test/patterns/redundant_catch/Simple.java
test/patterns/redundant_catch/TrickyFake.java
test/patterns/redundant_catch/TryInsideAnonymous.java
test/patterns/redundant_catch/TryInsideCatch.java
test/patterns/redundant_catch/TryInsideFinally.java
test/patterns/redundant_catch/TryInsideTry.java
test/patterns/redundant_catch/test_redundant_catch.py

https://github.com/yegor256/aibolit/issues/96

Pattern for redundant catch

---

aibolit/patterns/empty_rethrow/empty_rethrow.py
test/patterns/empty_rethrow/Anonymous.java
test/patterns/empty_rethrow/BothCatches.java
test/patterns/empty_rethrow/CatchWithFunctions.java
test/patterns/empty_rethrow/CatchWithIf.java
test/patterns/empty_rethrow/Empty.java
test/patterns/empty_rethrow/MultipleCatch.java
test/patterns/empty_rethrow/SequentialCatch.java
test/patterns/empty_rethrow/SequentialCatchTry.java
test/patterns/empty_rethrow/Simple.java
test/patterns/empty_rethrow/TrickyFake.java
test/patterns/empty_rethrow/TryInsideCatch.java
test/patterns/empty_rethrow/TryInsideFinally.java
test/patterns/empty_rethrow/TryInsideTry.java
test/patterns/empty_rethrow/test_empty_rethrow.py
test/patterns/null_check/NullCheck.java

https://github.com/yegor256/aibolit/issues/95

Empty Rethrow pattern

---

test/metrics/spaces/TestSpaces.py
test/patterns/er_class/test_er_class.py
test/patterns/force_type_casting_finder/test_force_type_casting_finder.py
test/patterns/if_return_if_detection/test_if_return_if.py
test/patterns/implements_multi/test_implements_multi.py
test/patterns/instanceof/test_instanceof.py
test/patterns/method_chaining/test_method_chaining.py
test/patterns/multiply_try/test_multiple_try.py
test/patterns/nested_blocks/test_nested_blocks.py
test/patterns/string_concat/test_concat_string.py
test/patterns/supermethod/test_supermethod.py
test/patterns/this_finder/test_find_this.py
test/patterns/var_decl_diff/test_var_decl_diff.py
test/patterns/var_middle/test_var_middle.py

Replace bare `assert` statements with `unittest.TestCase` assertion methods

---

SCOPE.md

Scope of work how we see at the beginning of the April

scope of work planning, April

---

aibolit/patterns/public_static_method/public_static_method.py
test/patterns/public_static_method/PublicStaticMethod.java
test/patterns/public_static_method/test_public_static_method.py

For #126: added public static method pattern and tests

For #126: added public static method pattern

---

PATTERNS.md
aibolit/patterns/private_static_method/private_static_method.py
test/patterns/private_static_method/PrivateStaticMethod.java
test/patterns/private_static_method/test_private_static_method.py

For #127: created private static method pattern and test

For #127: created private static method pattern

---

aibolit/patterns/partial_synchronized/partial_synchronized.py
aibolit/patterns/redundant_catch/redundant_catch.py
test/patterns/redundant_catch/NotThrow.java
test/patterns/redundant_catch/test_redundant_catch.py

https://github.com/yegor256/aibolit/issues/172

Fix for Redundant catch

---

aibolit/patterns/var_middle/var_middle.py

fixed issue #177

---

aibolit/patterns/empty_rethrow/empty_rethrow.py
aibolit/utils/ast.py
test/patterns/empty_rethrow/CommonRdbmsReader.java
test/patterns/empty_rethrow/ConcurrentDiskUtil.java
test/patterns/empty_rethrow/ConfigImportWizardPageDbvis.java
test/patterns/empty_rethrow/DataBaseNavigator.java
test/patterns/empty_rethrow/DatabaseNavigatorSourceContainer.java
test/patterns/empty_rethrow/test_empty_rethrow.py

Fixing https://github.com/yegor256/aibolit/issues/180

Fix empty rethrow when we have chaining exceptions

---

PATTERNS.md
aibolit/patterns/nested_loop/nested_loop.py
test/patterns/nested_loop/1.java
test/patterns/nested_loop/2.java
test/patterns/nested_loop/3.java
test/patterns/nested_loop/4.java
test/patterns/nested_loop/test_nested_loop.py

Pattern: Nested Loop 

---

aibolit/metrics/spaces/SpaceCounter.py
test/metrics/spaces/ClusterDataSourceConfiguration.java
test/metrics/spaces/TestSpaces.py
test/metrics/spaces/package-info.java

fixing https://github.com/yegor256/aibolit/issues/192

Fix case for SpaceCounter when we have 0 or 1 lines

---

aibolit/metrics/maxDiameter/FindMaxDiam.py
aibolit/metrics/maxDiameter/README.md
test/metrics/maxDiameter/1.java
test/metrics/maxDiameter/2.java
test/metrics/maxDiameter/3.java
test/metrics/maxDiameter/4.java
test/metrics/maxDiameter/5.java
test/metrics/maxDiameter/6.java
test/metrics/maxDiameter/test_FindMaxDiam.py

Added new metric of max diameter in AST (Fixed #167 Issue)

---

PATTERNS.md
aibolit/patterns/non_final_class/non_final_class.py
test/patterns/non_final_class/1.java
test/patterns/non_final_class/2.java
test/patterns/non_final_class/3.java
test/patterns/non_final_class/test_non_final_class.py

Pattern: class have to be final

---

aibolit/metrics/countLeaves/README.md
aibolit/metrics/countLeaves/numberofleaves.py
test/metrics/countLeaves/1.java
test/metrics/countLeaves/2.java
test/metrics/countLeaves/3.java
test/metrics/countLeaves/4.java
test/metrics/countLeaves/5.java
test/metrics/countLeaves/simple.java
test/metrics/countLeaves/test_countLeaves.py

fixed issue. added metric of leaves number

---

aibolit/metrics/cognitiveC/README.md
aibolit/metrics/cognitiveC/cognitive_c.py
test/metrics/cognitiveC/1.java
test/metrics/cognitiveC/2.java
test/metrics/cognitiveC/test_cognitive_c.py

#206  First step for impelementing cognitive complexity.
Me and @lukyanoffpashok view only two simple instances how cognitive complexity need to be considered.
We implemented incrementing only for and if - elif statements without nesting firstly.

started impelement cognitive complexity

---

aibolit/patterns/array_as_argument/array_as_argument.py
test/patterns/array_as_argument/ArrayAsArgument.java
test/patterns/array_as_argument/GenericArrayAsArgument.java
test/patterns/array_as_argument/NoArgument.java
test/patterns/array_as_argument/ObjectAsArgument.java
test/patterns/array_as_argument/PrimitiveAndArrayAsArgument.java
test/patterns/array_as_argument/PrimitiveAsArgument.java
test/patterns/array_as_argument/test_array_as_argument.py

For #136:
- added array as argument pattern
- added basic test cases

For #136: added array as argument pattern

---

aibolit/metrics/cognitiveC/cognitive_c.py
test/metrics/cognitiveC/3.java
test/metrics/cognitiveC/test_cognitive_c.py

Here me and @lukyanoffpashok  implemented opportunity to take into account nesting level in Cognitive complexity metric.
Solved https://github.com/yegor256/aibolit/issues/212

Cognitive complexity. Added considering nesting level

---

aibolit/patterns/var_siblings/var_siblings.py
test/patterns/var_siblings/AlternateVarSiblings.java
test/patterns/var_siblings/SimpleVarSiblings.java
test/patterns/var_siblings/test_var_siblings.py

For #141:
- implemented test cases for var_sibling pattern
- left puzzle for implementing var_sibling pattern

For #141: Var_sibling implementation start

---

aibolit/metrics/cognitiveC/cognitive_c.py
test/metrics/cognitiveC/4.java
test/metrics/cognitiveC/5.java
test/metrics/cognitiveC/6.java
test/metrics/cognitiveC/test_cognitive_c.py

Solved https://github.com/yegor256/aibolit/issues/216 
Here is only one problem - javalang can't recognize logical operator as '!'.
Have already formed issue about it: https://github.com/c2nes/javalang/issues/76

Cognitive complexity. Added an opportunity to increment logical operators correctly

---

aibolit/utils/ast.py
test/utils/test_ast.py

For #158 
- wrong file extension now raises exception on AST
- created test for this case

For #158: added file extension check for AST

---

aibolit/patterns/var_middle/var_middle.py
aibolit/utils/lines.py
test/utils/Lines/SimpleLinesTest.java
test/utils/Lines/test_lines.py

For #160 
- Created `Lines` class which extracts AST and line numbers from a file
- Created simple tests for `Line`
- Removed outdated method from `var_middle.py`

For #160: created Lines class to return AST lines

---

aibolit/patterns/method_siblings/method_siblings.py
test/patterns/method_siblings/AlternateMethodSiblings.java
test/patterns/method_siblings/SimpleMethodSiblings.java
test/patterns/method_siblings/test_method_siblings.py

For #142: 
- created test for most common cases in `method_sibling`
- left puzzle for `method_sibling` implementation

For #142: method_sibling tests

---

aibolit/metrics/external_methods_called/external_methods_called.py
test/metrics/external_methods_called/DoubleExternalMethodCalls.java
test/metrics/external_methods_called/ExternalMethodCalls.java
test/metrics/external_methods_called/InnerClassExternalMethodCalls.java
test/metrics/external_methods_called/NoExternalMethodCalls.java
test/metrics/external_methods_called/test_external_methods_called.py

For #183: 
- Added tests for number of external methods called
- left puzzle for implementation

For #183: Added tests for number of external methods called

---

aibolit/patterns/this_finder/this_finder.py
test/patterns/this_finder/BookmarkEditCmd.java
test/patterns/this_finder/ChainedBuffer.java
test/patterns/this_finder/CliMethodExtraSections.java
test/patterns/this_finder/LengthStringOrdinalSet.java
test/patterns/this_finder/LoaderInfoHeader.java
test/patterns/this_finder/OmfModuleEnd.java
test/patterns/this_finder/test_find_this.py

For #194:
Added the clases to this_finder tests:
- `BookMarkEditCmd. java` does not have any pattern to be found by `this_find`
- `ChainedBuffer. java` throws an exception
- `CliMethodExtraSections. java` does not have any pattern to be found by `this_find`
- `LoaderInfoHeader. java` throws an exception
- `OmfModuleEnd. java` does not have any pattern to be found by `this_find`

For #194: added tests to this_finder

---

aibolit/patterns/protected_method/protected_method.py
test/patterns/protected_method/AnonymousClassProtectedMethod.java
test/patterns/protected_method/InnerClassProtectedMethod.java
test/patterns/protected_method/NoProtectedMethod.java
test/patterns/protected_method/ProtectedMethod.java
test/patterns/protected_method/test_protected_method.py

For #164: protected_method pattern + tests have been added

---

aibolit/patterns/bidirect_index/bidirect_index.py
test/patterns/bidirect_index/BidirectIndexDecreaseIncrease.java
test/patterns/bidirect_index/BidirectIndexHiddenScope.java
test/patterns/bidirect_index/BidirectIndexIncreaseAssignmentDecrease.java
test/patterns/bidirect_index/BidirectIndexIncreaseAssignmentDecreaseAssignment.java
test/patterns/bidirect_index/BidirectIndexIncreaseDecrease.java
test/patterns/bidirect_index/BidirectIndexIncreaseDecreaseAssignment.java
test/patterns/bidirect_index/BidirectIndexOutsider.java
test/patterns/bidirect_index/test_bidirect_index.py

For #139: 
- added bidirect index tests
- left puzzle for implementation

For #139: added bidirect index tests

---

docker/Dockerfile
docker/Dockerfile.download

Two docker images:
1. image contains dataset and other artifacts Aibolit need
2. image prepares an environment to train a model

Dockerfile with dataset and other dependencies

---

aibolit/patterns/loop_outsider/loop_outsider.py
test/patterns/loop_outsider/LoopOutsiderAddAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderAssignmentInWhile.java
test/patterns/loop_outsider/LoopOutsiderBitwiseAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderBitwiseExclusiveOrInWhile.java
test/patterns/loop_outsider/LoopOutsiderBitwiseInclusiveOrInWhile.java
test/patterns/loop_outsider/LoopOutsiderDivideAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderLeftShiftAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderModulusAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderMultiplyAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderPostfixDecrementInWhile.java
test/patterns/loop_outsider/LoopOutsiderPostfixIncrementInWhile.java
test/patterns/loop_outsider/LoopOutsiderPrefixDecrementInWhile.java
test/patterns/loop_outsider/LoopOutsiderPrefixIncrementInWhile.java
test/patterns/loop_outsider/LoopOutsiderRightShiftAndInWhile.java
test/patterns/loop_outsider/LoopOutsiderSubtractAndInWhile.java
test/patterns/loop_outsider/test_loop_outsider.py

For #138: 
- added while loop tests for loop outsider pattern
- left puzzle for implementing for and do-while loops; making all the tests in just one PR would make it too big

For #138: added while loop tests for loop outsider pattern

---

README.md
docker/Dockerfile.recommend
docker/git_clone_and_pull_pr.sh

Base docker image to do a Aibolit's recommendation for the entire folder with Java classes

Dockerfile for recommendation pipeline

---

aibolit/patterns/partial_synchronized/partial_synchronized.py
test/integration/all.py
test/patterns/partial_synchronized/Constructor.java
test/patterns/partial_synchronized/Lambda.java
test/patterns/partial_synchronized/test_partial_synchronized.py

https://github.com/yegor256/aibolit/issues/260

Fix part sync with ctrs and lambdas

---

aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Fixing 
https://github.com/yegor256/aibolit/issues/263
https://github.com/yegor256/aibolit/issues/264

Recommend fixes

---

aibolit/patterns/joined_validation/joined_validation.py
test/integration/all.py
test/integration/samples/AbstractCommand.java
test/integration/samples/ActionHistory.java
test/integration/samples/ClipboardHandler.java
test/integration/samples/LiveMemoryViewUpdater.java
test/integration/samples/MethodsFeatureModes.java
test/integration/samples/MfLexer.java
test/integration/samples/ModifierEditor.java
test/integration/samples/ProfilerGCXYItemPainter.java
test/patterns/joined_validation/NoJoinedValidation.java

For #265:
- fixed `joined_validation` problems
- added a test sample to assure it
I extracted all the files in https://github.com/yegor256/aibolit/files/4586331/files.tar.gz and executed the script in https://github.com/yegor256/aibolit/files/4586321/temp.py.txt. No exception was raised.

For #265: joined_validation bug fixes

---

aibolit/__main__.py

fixing https://github.com/yegor256/aibolit/issues/287

Recommend failed when there is no recommendation

---

README.md
aibolit/__main__.py

fixing https://github.com/yegor256/aibolit/issues/298

Docs update

---

aibolit/model/model.py

Aibolit threshold. Wrong inequality fixed

---

PATTERNS.md
README.md

fixing https://github.com/yegor256/aibolit/issues/300

update docs for patterns

---

PATTERNS.md
aibolit/__main__.py
scripts/04-find-patterns.py

Add parameter to skip dataset collection
https://github.com/yegor256/aibolit/issues/315

Skip collect dataset

---

README.md
aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Add full report for xml

---

aibolit/__main__.py
aibolit/metrics/entropy/entropy.py
aibolit/metrics/ncss/ncss.py
aibolit/metrics/spaces/SpaceCounter.py
aibolit/patterns/assign_null_finder/assign_null_finder.py
aibolit/patterns/non_final_attribute/non_final_attribute.py
aibolit/patterns/string_concat/string_concat.py
aibolit/patterns/supermethod/supermethod.py
aibolit/utils/ast.py
aibolit/utils/lines.py
appveyor.yml
test/integration/samples/ConditionalExpressionCheck.java
test/integration/samples/ExceptionDemo.java
test/utils/ConditionalExpressionCheck.java
test/utils/ExceptionDemo.java
test/utils/test_ast.py

Fix encoding bug

---

README.md
aibolit/__main__.py
aibolit/model/model.py
test/recommend/test_recommend_pipeline.py

fix https://github.com/yegor256/aibolit/issues/327

Add score to xml

---

aibolit/__main__.py

Fix parameter full_report

---

aibolit/__main__.py
aibolit/ml_pipeline/ml_pipeline.py
aibolit/model/model.py

Create parameter with output dataset file

---

README.md
aibolit/__main__.py

Return exit_code

---

aibolit/config.py
aibolit/ml_pipeline/ml_pipeline.py
aibolit/model/model.py
scripts/03-calculate-metrics.py

Fix #322
1) remove cat_boost folder with logs
2) fix \n in the logs. Now training has a good human-readable output

Fix logs output

---

aibolit/patterns/non_final_argument/NonFinalArgumentCtor.java
aibolit/patterns/non_final_argument/NonFinalArgumentMethod.java
aibolit/patterns/non_final_argument/non_final_argument.py
test/patterns/non_final_argument/test_non_final_argument.py

For #146: Added non final argument pattern tests:
- for non-final argument in constructors
- for non-final agument in method
- left puzzle for pattern implementation

For #146: non final argument pattern

---

scripts/02-filter-and-move.py

fix https://github.com/yegor256/aibolit/issues/337

Fix multi-threaded with max-classes

---

README.md
aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Fix output for format=long

---

aibolit/__main__.py

Remove package-info.java from recommend

---

aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Fix #358 "some issues found" is redundant message in the log

---

README.md
aibolit/__main__.py

Rename recommend to check

---

README.md
aibolit/__main__.py

fix https://github.com/yegor256/aibolit/issues/356

Model name

---

PATTERNS.md
aibolit/config.py
test/recommend/test_recommend_pipeline.py

Fix https://github.com/yegor256/aibolit/issues/376

Fixed docs and config

---

aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Fixed output

---

README.md
aibolit/config.py
setup.py

fix https://github.com/yegor256/aibolit/issues/318

Fix docs in setup.py + Docs fix

---

aibolit/__main__.py

fix https://github.com/yegor256/aibolit/issues/384

Add format=short

---

README.md
aibolit/__main__.py
aibolit/config.py
test/recommend/test_recommend_pipeline.py

Suppress parameter

---

aibolit/patterns/if_return_if_detection/if_detection.py
aibolit/patterns/joined_validation/joined_validation.py
aibolit/patterns/partial_synchronized/partial_synchronized.py
aibolit/patterns/redundant_catch/redundant_catch.py
aibolit/patterns/var_decl_diff/var_decl_diff.py
aibolit/patterns/var_middle/var_middle.py
aibolit/utils/java_parser.py
aibolit/utils/lines.py
aibolit/utils/scope_status.py
test/patterns/partial_synchronized/test_partial_synchronized.py
test/patterns/redundant_catch/test_redundant_catch.py
test/patterns/var_decl_diff/test_var_decl_diff.py
test/patterns/var_middle/15.java
test/patterns/var_middle/test_var_middle.py

Var in the middle pattern is rewritten to traverse full tree instead of flattening it.
New test from the issue is added.

Traversing AST for var in the middle pattern.

---

aibolit/patterns/var_middle/var_middle.py
test/patterns/var_middle/16.java
test/patterns/var_middle/test_var_middle.py

Now TypeParameter is ignored node.

Fix #365. Var in the middle for lambda test.

---

aibolit/__main__.py

Now aibolit can check the latest version available

---

aibolit/config.py
aibolit/patterns/nested_blocks/nested_blocks.py

include P31, P32 patterns into config (uncomment)

---

aibolit/config.py

Fix config #401 

---

README.md

fix https://github.com/yegor256/aibolit/issues/385

Fix readme #385

---

aibolit/__main__.py
aibolit/model/model.py
test/model/test_model.py
test/recommend/test_recommend_pipeline.py

fix https://github.com/yegor256/aibolit/issues/407

Release 1.1.0

---

aibolit/__main__.py
aibolit/model/model.py

fix #422 
```
$ aibolit --help
Version 1.1.0 is available, but you are using 0.0.0
usage: aibolit <command> [<args>]
You can run 1 command:
train          Train model
check          Recommend pattern
recommend      Recommend pattern. The same as recommend, just another acronym
Find the pattern which has the largest impact on readability
positional arguments:
command     Subcommand to run
optional arguments:
-h, --help  show this help message and exit
--version   show program's version number and exit
```
```$ aibolit check --help
Version 1.1.0 is available, but you are using 0.0.0
usage: aibolit check < --folder | --filenames > [--model] [--threshold] [--full] [--format]
Get recommendations for Java code
optional arguments:
-h, --help            show this help message and exit
--folder …
```

Fix output

---

README.md
aibolit/__main__.py

fix https://github.com/yegor256/aibolit/issues/363

Fix issue 363

---

aibolit/ml_pipeline/ml_pipeline.py
aibolit/model/model.py

Release 1.1.2 #443 

---

aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

fix https://github.com/yegor256/aibolit/issues/429

Add new lines with summary info (Fix $429)

---

aibolit/patterns/assert_in_code/assert_in_code.py
aibolit/patterns/force_type_casting_finder/force_type_casting_finder.py
aibolit/patterns/instanceof/instance_of.py
aibolit/patterns/multiple_while/multiple_while.py
aibolit/patterns/var_middle/var_middle.py
aibolit/utils/ast.py
aibolit/utils/java_class_method.py
aibolit/utils/java_package.py
test/utils/MemberReferencesExample.java
test/utils/MethodInvokeExample.java
test/utils/MethodUseOtherMethodExample.java
test/utils/test_ast.py
test/utils/test_java_class_method.py

Also added `parameters` property to view parameters of method.
AST constructor changed to be more simple. Constructing AST from javalang node is now done by static method.

Used_fields property for java methods.

---

aibolit/__main__.py

https://github.com/yegor256/aibolit/issues/461

Fix ncss = 0

---

aibolit/__main__.py
aibolit/metrics/RFC/rfc.py
test/metrics/RFC/1.java
test/metrics/RFC/2.java
test/metrics/RFC/3.java
test/metrics/RFC/4.java
test/metrics/RFC/5.java
test/metrics/RFC/test_all_types.py

RFC implementation

---

scripts/02-filter-and-move.py

fix https://github.com/yegor256/aibolit/issues/476

Ignore nested classes in dataset

---

scripts/02-filter-and-move.py

fix https://github.com/cqfn/aibolit/issues/480

Filter test and train

---

aibolit/__main__.py
test/recommend/start_end/AnonymousClass.java
test/recommend/start_end/EmptyFunction.java
test/recommend/start_end/Lambda.java
test/recommend/start_end/LottieImageAsset.java
test/recommend/start_end/OneLineFunction.java
test/recommend/test_recommend_pipeline.py

Fixing https://github.com/cqfn/aibolit/issues/495
part of #462

Function for find start and end lines for node

---

aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Fix https://github.com/cqfn/aibolit/issues/502

Add function to filter ignored patterns

---

aibolit/__main__.py

fix https://github.com/cqfn/aibolit/issues/491

Fix timeout issue

---

aibolit/ast_framework/ast.py
aibolit/ast_framework/ast_node.py
aibolit/metrics/ncss/ncss.py
test/metrics/ncss/BasicExample.java
test/metrics/ncss/ChainedIfElse.java
test/metrics/ncss/ChainedIfElseWithTrailingElse.java
test/metrics/ncss/Empty.java
test/metrics/ncss/FinallyBlock.java
test/metrics/ncss/Simple.java
test/metrics/ncss/SimpleExample.java
test/metrics/ncss/SimpleExample2.java
test/metrics/ncss/test_all_types.py

- New tests were added
- Corrected errors in mark up in existing tests
- Now counting else keywords

NCSS metric with new API.

---

aibolit/ast_framework/ast.py
aibolit/ast_framework/ast_node_type.py

Improve ast printing.

---

aibolit/patterns/non_final_attribute/non_final_attribute.py

refactored NonFinalAttribute

---

aibolit/patterns/null_check/null_check.py
test/patterns/null_check/1.java
test/patterns/null_check/2.java
test/patterns/null_check/3.java
test/patterns/null_check/4.java
test/patterns/null_check/5.java
test/patterns/null_check/test_null_check.py

refactored nullcheck pattern and rewrote tests

---

aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

fix https://github.com/cqfn/aibolit/issues/565

Fix bug when aibolit fails if we have any error when pattern calculation

---

aibolit/patterns/send_null/send_null.py
test/patterns/send_null/test_send_null.py

fix https://github.com/cqfn/aibolit/issues/575

Rewrite Send null with ASTNode

---

aibolit/__main__.py
test/recommend/start_end/FileStorage.java
test/recommend/test_recommend_pipeline.py

fix https://github.com/cqfn/aibolit/issues/585

Fix issue with SupressWarnings

---

.github/pull_request_template.md

closes #593 
This is a template for PRs. To unify. Please review and make suggestions.

GitHub Pull Request Template

---

wp/sections/usage_scenarios.tex

Aibolit WP: fix typo and grammar error

---

wp/wp.tex

Aibolit WP:  make it more clear: we have to avoid "bad" patterns

---

wp/sections/usage_scenarios.tex

closes #603 
the long sentence is split and written simpler.

Aibolit WP: split long sentence. 

---

PATTERNS.md
aibolit/__main__.py

Please specify the following in the description:
1. Fix #608
2. Docs are updated

Fix docs in aibolit

---

PATTERNS.md
aibolit/__main__.py
test/recommend/test_recommend_pipeline.py

Please specify the following in the description:
1. Fix #609 
2. Fixes output

Fix output (Yegor's issue)

---

scripts/04-find-patterns.py

Fix pattern calculation.

---

aibolit/__main__.py
aibolit/config.py
aibolit/metrics/RFC/rfc.py
aibolit/ml_pipeline/ml_pipeline.py
aibolit/model/model.py
aibolit/model/stats.py
scripts/04-find-patterns.py
test/integration/test_model.py

Fix #632 
Added ability to choose target metric to be trained against.
Currently supported:
- Cognitive complexity
- Fan out
- Max methods diameter
- Response for a class

Multitargeting

---

Makefile
aibolit/extract_method_baseline/extract_semantic.py
test/extract_method_baseline/SimpleMethods.java
test/extract_method_baseline/test_extract_semantic.py
test/integration/test_semantic_extraction.py

Fix #636, based on #635.
Add support for complext statements. Add integration tests.

Extract semantic for complex statements.

---

Makefile
aibolit/metrics/loc/loc.py
requirements.txt

This PR attempts to fix `ruff` CI workflow.
For convenience I added `make ruff` step, which is useful during development.
The workflow complained about one file, which I refactored to fix the problem.
- https://github.com/cqfn/aibolit/blob/master/aibolit/metrics/loc/loc.py
Closes #710

Fix ruff workflow

---

aibolit/metrics/external_methods_called/external_methods_called.py
test/metrics/external_methods_called/test_external_methods_called.py

This PR implements `ExternalMethodsCalled` metric.
Closes #740

Implement `ExternalMethodsCalled` metric

---

aibolit/metrics/npath/main.py
test/metrics/npath/test_all_types.py

In this PR we add mvn-free npath metric implementation for switch statements.
Closes #799

Add mvn-free npath metric implementation for switch statements

---

aibolit/metrics/npath/main.py
test/metrics/npath/test_all_types.py

This PR implements `MvnFreeNpathMetric` for binary AND condition.
OR condition was added as a puzzle.
Closes #805

Implement `MvnFreeNpathMetric` for binary AND condition
